console_title_template = '{{ .Shell }} in {{ .Folder }}'
version = 3
final_space = true
enable_cursor_positioning = true

[palette]
  black					= '#22262e'
  grey					= "#494d55"
  light_grey    = "#676b73"
  white					= '#bbc2cf'
  blue					= '#51afef'
  nord_blue			= "#47a5e5"
  teal					= "#4db5bd"
  cyan					= "#46D9FF"
  green					= '#98be65'
  vibrant_green = '#a9cf76'
  yellow				= '#ECBE7B'
  sun					  = '#f2c481'
  orange				= '#ea9558'
  red					  = '#ff6b5a'
  baby_pink			= "#ff7665"
  pink					= "#ff75a0"
  purple				= '#dc8ef3'
  dark_purple		= '#c678dd'

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    template = '{{ .Icon }} '
    foreground = 'p:nord_blue'
    background = 'transparent'
    type = 'os'
    style = 'plain'

  [[blocks.segments]]
    template = ' {{ if .Writable }} {{ else }} {{ end }}{{ path .Path .Location }} '
    foreground = 'p:white'
    background = 'transparent'
    type = 'path'
    style = 'plain'

    [blocks.segments.properties]
      style = 'agnoster_full'

  [[blocks.segments]]
    template = ' {{ if .UpstreamURL }}{{ url .UpstreamIcon .UpstreamURL }} {{ end }}{{ .HEAD }}{{if .BranchStatus }} {{ .BranchStatus }}{{ end }}{{ if .Working.Changed }}  {{ .Working.String }}{{ end }}{{ if .Staging.Changed }}  {{ .Staging.String }}{{ end }} '
    foreground = 'p:green'
    background = 'transparent'
    type = 'git'
    style = 'plain'
    foreground_templates = ['{{ if or (.Working.Changed) (.Staging.Changed) }}p:yellow{{ end }}', '{{ if and (gt .Ahead 0) (gt .Behind 0) }}p:red{{ end }}', '{{ if gt .Ahead 0 }}p:dark_purple{{ end }}', '{{ if gt .Behind 0 }}p:purple{{ end }}']

    [blocks.segments.properties]
      branch_max_length = 25
      fetch_status = true
      fetch_upstream_icon = true

  [[blocks.segments]]
    template = '  '
    foreground = 'p:sun'
    background = 'transparent'
    type = 'root'
    style = 'plain'

[[blocks]]
  type = 'rprompt'
  overflow = 'hidden'

  [[blocks.segments]]
    template = ' '
    foreground = 'p:green'
    background = 'transparent'
    type = 'node'
    style = 'plain'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_package_manager = false
      home_enabled = false

  [[blocks.segments]]
    template = ' '
    foreground = 'p:blue'
    background = 'transparent'
    type = 'go'
    style = 'plain'

    [blocks.segments.properties]
      fetch_version = false

  [[blocks.segments]]
    template = ' '
    foreground = 'p:yellow'
    background = 'transparent'
    type = 'python'
    style = 'plain'

    [blocks.segments.properties]
      display_mode = 'files'
      fetch_version = false
      fetch_virtual_env = false

  [[blocks.segments]]
    template = '{{ if .SSHSession }}  {{ .UserName }}@{{ .HostName }} {{ end }}'
    foreground = 'p:white'
    background = 'transparent'
    type = 'session'
    style = 'plain'

  [[blocks.segments]]
    template = '  {{ .FormattedMs }} '
    foreground = 'p:cyan'
    background = 'transparent'
    type = 'executiontime'
    style = 'plain'

    [blocks.segments.properties]
      threshold = 500
      style = 'austin'

[[tooltips]]
  template = '  {{ .Profile }}{{ if .Region }}@{{ .Region }}{{ end }} '
  foreground = 'p:orange'
  background = 'transparent'
  type = 'aws'
  style = 'plain'
  tips = ['aws']

  [tooltips.properties]
    display_default = true

[[tooltips]]
  template = '  {{ .Name }} '
  foreground = 'p:blue'
  background = 'transparent'
  type = 'az'
  style = 'plain'
  tips = ['az']

  [tooltips.properties]
    display_default = true

[[blocks]]
  type = 'prompt'
  alignment = 'left'
  newline = true

  [[blocks.segments]]
    type = 'text'
    style = 'plain'
    foreground_templates = [
      "{{if gt .Code 0}}red{{end}}",
      "{{if eq .Code 0}}p:green{{end}}",
    ]
    background = 'transparent'
    template = '❯'

[transient_prompt]
  template = '❯ '
  foreground_templates = [
    "{{if gt .Code 0}}p:red{{end}}",
    "{{if eq .Code 0}}p:green{{end}}",
  ]
  background = 'transparent'

[secondary_prompt]
  template = '❯❯ '
  foreground = 'p:green'
  background = 'transparent'
